apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: catalog-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/prod/catalog-microservice
        property: DATABASE_URL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/catalog-microservice
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/prod/auth-microservice
        property: JWT_SECRET
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: secret/prod/minio-microservice
        property: MINIO_ROOT_PASSWORD

    - secretKey: JWT_TOKEN
      remoteRef:
        key: secret/prod/catalog-microservice
        property: JWT_TOKEN
    - secretKey: WAREHOUSE_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/catalog-microservice
        property: WAREHOUSE_SERVICE_TOKEN
    - secretKey: CATALOG_SMOKE_BAZOS_PRODUCT_ID
      remoteRef:
        key: secret/prod/catalog-microservice
        property: CATALOG_SMOKE_BAZOS_PRODUCT_ID
    - secretKey: CATALOG_SMOKE_BAZOS_IDENTITY_ID
      remoteRef:
        key: secret/prod/catalog-microservice
        property: CATALOG_SMOKE_BAZOS_IDENTITY_ID
    - secretKey: CATALOG_SMOKE_BAZOS_CATEGORY
      remoteRef:
        key: secret/prod/catalog-microservice
        property: CATALOG_SMOKE_BAZOS_CATEGORY
    - secretKey: CATALOG_SMOKE_BAZOS_LOCATION
      remoteRef:
        key: secret/prod/catalog-microservice
        property: CATALOG_SMOKE_BAZOS_LOCATION
    - secretKey: BAZOS_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/catalog-microservice
        property: BAZOS_SERVICE_TOKEN
    - secretKey: CATALOG_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/auth-microservice
        property: CATALOG_INTERNAL_SERVICE_TOKEN
